config/routes.rb
Rails.application.routes.draw do
  root 'snaps#index'

  resources :snaps
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/snap.rb
class Snap < ActiveRecord::Base
  validates :photo, presence: true

  has_attached_file :photo,
  styles: {
    :thumb => "150x150>",
    :medium => "500x500>",
    :large => "1280x960>"
  }

  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/snaps_controller.rb
class SnapsController < ApplicationController
  def index
    @snaps = Snap.all
  end

  def new
    @snap = Snap.new
  end

  def create
    @snap = Snap.create(snap_params)
    redirect_to snaps_path
  end


  private

  def snap_params
    params.require(:snap).permit(:photo, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/snap_helper.rb
module SnapHelper
end

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default
  .navbar-container
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle Navigation
        %span.icon-bar
        %span.icon-bar
      .navbar-brand= link_to "Instaphoto", root_path
    .collapse.navbar-collapse#bs-navbar-collapse-1
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to "New Snap", new_snap_path
        %li
          = link_to "Login", "#"
        %li
          = link_to "Register", "#"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Instaphoto</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>

<%= yield %>

</body>
</html>

app/views/snaps/index.html.haml
%h1 Photogram

-@snaps.each do |snap|
  .row
    =link_to (image_tag snap.photo.url(:medium)), snap_path(snap)
    %p= snap.description

app/views/snaps/new.html.haml
= simple_form_for @snap do |f|
  = f.input :photo
  = f.input :description
  = f.button :submit